# Generated by Django 5.2.6 on 2025-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('deck_box', 'Deck Box'), ('sleeves', 'Card Sleeves'), ('playmat', 'Playmat'), ('booster_box', 'Booster Box'), ('starter_deck', 'Starter Deck'), ('structure_deck', 'Structure Deck'), ('tin', 'Collector Tin'), ('accessory', 'Gaming Accessory'), ('merchandise', 'Merchandise')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('opened', 'Opened'), ('used', 'Used'), ('damaged', 'Damaged')], default='new', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='other_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('quantity_per_pack', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
