# Generated by Django 5.2.6 on 2025-11-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='other_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.otherproduct'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('super_rare', 'Super Rare'), ('ultra_rare', 'Ultra Rare'), ('secret_rare', 'Secret Rare'), ('ghost_rare', 'Ghost Rare'), ('parallel_rare', 'Parallel Rare'), ('gold_rare', 'Gold Rare'), ('starlight_rare', 'Starlight Rare'), ('starfoil_rare', 'Starfoil Rare'), ('prismatic_rare', 'Prismatic Secret Rare'), ('quarter_century_rare', 'Quarter Century Secret Rare'), ('ultimate_rare', 'Ultimate Rare'), ('collector_rare', 'Collector Rare')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'card'], name='cards_carti_user_id_6a9194_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'other_product'], name='cards_carti_user_id_d9fd2c_idx'),
        ),
    ]
