# Generated by Django 5.2.6 on 2025-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0006_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardset",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="sets/"),
        ),
    ]
