# Generated by Django 5.2.6 on 2025-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_cardset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_shipping_fee', models.DecimalField(decimal_places=2, default=0, help_text='Phí giao hàng tiêu chuẩn', max_digits=10)),
                ('fast_shipping_fee', models.DecimalField(decimal_places=2, default=30000, help_text='Phí giao hàng nhanh', max_digits=10)),
                ('express_shipping_fee', models.DecimalField(decimal_places=2, default=50000, help_text='Phí giao hàng hỏa tốc', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=500000, help_text='Giá trị đơn hàng để miễn phí ship', max_digits=10)),
                ('standard_delivery_days', models.CharField(default='3-5 ngày làm việc', help_text='Thời gian giao hàng tiêu chuẩn', max_length=50)),
                ('fast_delivery_days', models.CharField(default='1-2 ngày làm việc', help_text='Thời gian giao hàng nhanh', max_length=50)),
                ('express_delivery_days', models.CharField(default='Trong ngày', help_text='Thời gian giao hàng hỏa tốc', max_length=50)),
                ('price_under_200k_inner', models.DecimalField(decimal_places=2, default=15000, help_text='Phí ship nội thành cho đơn dưới 200k', max_digits=10)),
                ('price_200_500k_inner', models.DecimalField(decimal_places=2, default=10000, help_text='Phí ship nội thành cho đơn 200k-500k', max_digits=10)),
                ('price_over_500k_inner', models.DecimalField(decimal_places=2, default=0, help_text='Phí ship nội thành cho đơn trên 500k', max_digits=10)),
                ('price_under_200k_outer', models.DecimalField(decimal_places=2, default=25000, help_text='Phí ship ngoại thành cho đơn dưới 200k', max_digits=10)),
                ('price_200_500k_outer', models.DecimalField(decimal_places=2, default=20000, help_text='Phí ship ngoại thành cho đơn 200k-500k', max_digits=10)),
                ('price_over_500k_outer', models.DecimalField(decimal_places=2, default=0, help_text='Phí ship ngoại thành cho đơn trên 500k', max_digits=10)),
                ('price_under_200k_province', models.DecimalField(decimal_places=2, default=35000, help_text='Phí ship tỉnh khác cho đơn dưới 200k', max_digits=10)),
                ('price_200_500k_province', models.DecimalField(decimal_places=2, default=30000, help_text='Phí ship tỉnh khác cho đơn 200k-500k', max_digits=10)),
                ('price_over_500k_province', models.DecimalField(decimal_places=2, default=0, help_text='Phí ship tỉnh khác cho đơn trên 500k', max_digits=10)),
                ('return_period_days', models.IntegerField(default=7, help_text='Số ngày cho phép đổi trả')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Settings',
                'verbose_name_plural': 'Shipping Settings',
            },
        ),
    ]
