# Generated by Django 5.2.6 on 2025-12-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_shippingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the slide', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('image', models.ImageField(help_text='Slider image (recommended: 1200x400px)', upload_to='hero_slider/')),
                ('link_url', models.CharField(blank=True, help_text='Optional link URL (e.g., card list filter)', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
